import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { runCli } from '../dist/index.js';

const lines = [];
await runCli(['hash', 'test/fixture.frontier'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines[0], /^fnv1a32:/);
lines.length = 0;
await runCli(['emit-ts', 'test/fixture.frontier'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines.join('\n'), /export interface Todo/);
lines.length = 0;
await runCli(['emit', 'test/fixture.frontier', '--target', 'javascript'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines.join('\n'), /export const TodoSchema/);
lines.length = 0;
await runCli(['ast', 'test/fixture.frontier', '--target', 'javascript'], { log: (value = '') => lines.push(String(value)) });
assert.equal(JSON.parse(lines.join('\n')).kind, 'javascript.module');
lines.length = 0;
await runCli(['capabilities', 'test/fixture.frontier', '--target', 'typescript', '--platform', 'node'], { log: (value = '') => lines.push(String(value)) });
assert.equal(JSON.parse(lines.join('\n'))[0].status, 'bound');
lines.length = 0;
await runCli(['emit', 'test/fixture.frontier', '--target', 'rust', '--ast'], { log: (value = '') => lines.push(String(value)) });
assert.equal(JSON.parse(lines.join('\n')).kind, 'rust.module');
lines.length = 0;
await runCli(['emit-rust', 'test/fixture.frontier'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines.join('\n'), /pub struct Todo/);
lines.length = 0;
await runCli(['to-json', 'test/fixture.frontier'], { log: (value = '') => lines.push(String(value)) });
const envelope = JSON.parse(lines.join('\n'));
assert.equal(envelope.kind, 'frontier.lang.universalAst');
const jsonPath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-json-')), 'fixture.frontier.json');
writeFileSync(jsonPath, lines.join('\n'));
lines.length = 0;
await runCli(['from-json', jsonPath, '--target', 'typescript'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines.join('\n'), /export interface Todo/);
lines.length = 0;
await runCli(['roundtrip', 'test/fixture.frontier', '--target', 'javascript'], { log: (value = '') => lines.push(String(value)) });
const roundtrip = JSON.parse(lines.join('\n'));
assert.equal(roundtrip.envelope.kind, 'frontier.lang.universalAst');
assert.match(roundtrip.output, /export const TodoSchema/);
const nativePath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-native-')), 'todo.js');
writeFileSync(nativePath, 'export function addTodo() { return null; }');
lines.length = 0;
await runCli(['import', nativePath, '--parser', 'estree'], { log: (value = '') => lines.push(String(value)) });
const nativeImport = JSON.parse(lines.join('\n'));
assert.equal(nativeImport.language, 'javascript');
assert.equal(nativeImport.universalAst.kind, 'frontier.lang.universalAst');
assert.equal(nativeImport.semanticIndex.symbols.some((symbol) => symbol.name === 'addTodo'), true);
assert.equal(nativeImport.sourceMaps[0].kind, 'frontier.lang.sourceMap');
assert.equal(nativeImport.sourceMaps[0].mappings.some((mapping) => mapping.semanticSymbolId.includes('addtodo')), true);
assert.equal(nativeImport.universalAst.sourceMaps[0].id, nativeImport.sourceMaps[0].id);
const nativeOutPath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-native-out-')), 'native-import.json');
lines.length = 0;
await runCli(['import', nativePath, '--parser', 'estree', '--out', nativeOutPath], { log: (value = '') => lines.push(String(value)) });
assert.equal(lines.length, 0);
const nativeOut = JSON.parse(readFileSync(nativeOutPath, 'utf8'));
assert.equal(nativeOut.semanticIndex.symbols[0].name, 'addTodo');
assert.equal(nativeOut.sourceMaps[0].mappings.some((mapping) => mapping.semanticSymbolId.includes('addtodo')), true);
const phpPath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-native-php-')), 'todo.php');
writeFileSync(phpPath, '<?php\nfunction addTodo($title) {}\n');
lines.length = 0;
await runCli(['import', phpPath], { log: (value = '') => lines.push(String(value)) });
const phpImport = JSON.parse(lines.join('\n'));
assert.equal(phpImport.language, 'php');
assert.equal(phpImport.semanticIndex.symbols.some((symbol) => symbol.name === 'addTodo'), true);
const rubyPath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-native-ruby-')), 'todo.rb');
writeFileSync(rubyPath, 'def add_todo(title)\nend\n');
lines.length = 0;
await runCli(['import', rubyPath], { log: (value = '') => lines.push(String(value)) });
const rubyImport = JSON.parse(lines.join('\n'));
assert.equal(rubyImport.language, 'ruby');
assert.equal(rubyImport.semanticIndex.symbols.some((symbol) => symbol.name === 'add_todo'), true);

const binDir = mkdtempSync(join(tmpdir(), 'frontier-lang-cli-bin-'));
const binPath = join(binDir, 'frontier-lang');
symlinkSync(join(process.cwd(), 'dist/index.js'), binPath);
const binRun = spawnSync(process.execPath, [binPath, 'hash', 'test/fixture.frontier'], { encoding: 'utf8' });
assert.equal(binRun.status, 0, binRun.stderr);
assert.match(binRun.stdout.trim(), /^fnv1a32:/);
