import assert from 'node:assert/strict';
import { mkdtempSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { runCli } from '../dist/index.js';

const lines = [];
await runCli(['hash', 'test/fixture.frontier'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines[0], /^fnv1a32:/);
lines.length = 0;
await runCli(['emit-ts', 'test/fixture.frontier'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines.join('\n'), /export interface Todo/);
lines.length = 0;
await runCli(['emit', 'test/fixture.frontier', '--target', 'javascript'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines.join('\n'), /export const TodoSchema/);
lines.length = 0;
await runCli(['ast', 'test/fixture.frontier', '--target', 'javascript'], { log: (value = '') => lines.push(String(value)) });
assert.equal(JSON.parse(lines.join('\n')).kind, 'javascript.module');
lines.length = 0;
await runCli(['capabilities', 'test/fixture.frontier', '--target', 'typescript', '--platform', 'node'], { log: (value = '') => lines.push(String(value)) });
assert.equal(JSON.parse(lines.join('\n'))[0].status, 'bound');
lines.length = 0;
await runCli(['emit', 'test/fixture.frontier', '--target', 'rust', '--ast'], { log: (value = '') => lines.push(String(value)) });
assert.equal(JSON.parse(lines.join('\n')).kind, 'rust.module');
lines.length = 0;
await runCli(['emit-rust', 'test/fixture.frontier'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines.join('\n'), /pub struct Todo/);

const binDir = mkdtempSync(join(tmpdir(), 'frontier-lang-cli-bin-'));
const binPath = join(binDir, 'frontier-lang');
symlinkSync(join(process.cwd(), 'dist/index.js'), binPath);
const binRun = spawnSync(process.execPath, [binPath, 'hash', 'test/fixture.frontier'], { encoding: 'utf8' });
assert.equal(binRun.status, 0, binRun.stderr);
assert.match(binRun.stdout.trim(), /^fnv1a32:/);
