import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { runCli } from '../dist/index.js';

const lines = [];
await runCli(['hash', 'test/fixture.frontier'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines[0], /^fnv1a32:/);
lines.length = 0;
await runCli(['emit-ts', 'test/fixture.frontier'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines.join('\n'), /export interface Todo/);
lines.length = 0;
await runCli(['emit', 'test/fixture.frontier', '--target', 'javascript'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines.join('\n'), /export const TodoSchema/);
lines.length = 0;
await runCli(['ast', 'test/fixture.frontier', '--target', 'javascript'], { log: (value = '') => lines.push(String(value)) });
assert.equal(JSON.parse(lines.join('\n')).kind, 'javascript.module');
lines.length = 0;
await runCli(['capabilities', 'test/fixture.frontier', '--target', 'typescript', '--platform', 'node'], { log: (value = '') => lines.push(String(value)) });
assert.equal(JSON.parse(lines.join('\n'))[0].status, 'bound');
lines.length = 0;
await runCli(['emit', 'test/fixture.frontier', '--target', 'rust', '--ast'], { log: (value = '') => lines.push(String(value)) });
assert.equal(JSON.parse(lines.join('\n')).kind, 'rust.module');
lines.length = 0;
await runCli(['emit-rust', 'test/fixture.frontier'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines.join('\n'), /pub struct Todo/);
lines.length = 0;
await runCli(['to-json', 'test/fixture.frontier'], { log: (value = '') => lines.push(String(value)) });
const envelope = JSON.parse(lines.join('\n'));
assert.equal(envelope.kind, 'frontier.lang.universalAst');
const jsonPath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-json-')), 'fixture.frontier.json');
writeFileSync(jsonPath, lines.join('\n'));
lines.length = 0;
await runCli(['from-json', jsonPath, '--target', 'typescript'], { log: (value = '') => lines.push(String(value)) });
assert.match(lines.join('\n'), /export interface Todo/);
lines.length = 0;
await runCli(['roundtrip', 'test/fixture.frontier', '--target', 'javascript'], { log: (value = '') => lines.push(String(value)) });
const roundtrip = JSON.parse(lines.join('\n'));
assert.equal(roundtrip.envelope.kind, 'frontier.lang.universalAst');
assert.match(roundtrip.output, /export const TodoSchema/);
const nativePath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-native-')), 'todo.js');
writeFileSync(nativePath, 'export function addTodo() { return null; }');
lines.length = 0;
await runCli(['import', nativePath, '--parser', 'estree'], { log: (value = '') => lines.push(String(value)) });
const nativeImport = JSON.parse(lines.join('\n'));
assert.equal(nativeImport.language, 'javascript');
assert.equal(nativeImport.universalAst.kind, 'frontier.lang.universalAst');
assert.equal(nativeImport.semanticIndex.symbols.some((symbol) => symbol.name === 'addTodo'), true);
assert.equal(nativeImport.sourceMaps[0].kind, 'frontier.lang.sourceMap');
assert.equal(nativeImport.sourceMaps[0].mappings.some((mapping) => mapping.semanticSymbolId.includes('addtodo')), true);
assert.equal(nativeImport.universalAst.sourceMaps[0].id, nativeImport.sourceMaps[0].id);
assert.equal(nativeImport.metadata.sourcePreservation.kind, 'frontier.lang.nativeSourcePreservation');
assert.equal(nativeImport.metadata.nativeImportLossSummary.semanticMergeReadiness, 'needs-review');
lines.length = 0;
await runCli(['import', nativePath, '--parser', 'estree', '--sidecar-only'], { log: (value = '') => lines.push(String(value)) });
const nativeSidecar = JSON.parse(lines.join('\n'));
assert.equal(nativeSidecar.kind, 'frontier.lang.semanticImportSidecar');
assert.equal(nativeSidecar.summary.symbols >= 1, true);
const nativeOutPath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-native-out-')), 'native-import.json');
lines.length = 0;
await runCli(['import', nativePath, '--parser', 'estree', '--out', nativeOutPath], { log: (value = '') => lines.push(String(value)) });
assert.equal(lines.length, 0);
const nativeOut = JSON.parse(readFileSync(nativeOutPath, 'utf8'));
assert.equal(nativeOut.semanticIndex.symbols[0].name, 'addTodo');
assert.equal(nativeOut.sourceMaps[0].mappings.some((mapping) => mapping.semanticSymbolId.includes('addtodo')), true);
lines.length = 0;
await runCli(['project-native', nativeOutPath], { log: (value = '') => lines.push(String(value)) });
const nativeProjection = JSON.parse(lines.join('\n'));
assert.equal(nativeProjection.kind, 'frontier.lang.nativeSourceProjection');
assert.equal(nativeProjection.mode, 'preserved-source');
assert.equal(nativeProjection.sourceText, readFileSync(nativePath, 'utf8'));
const nativeProjectionSourcePath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-native-source-out-')), 'todo.js');
lines.length = 0;
await runCli(['project-native', nativeOutPath, '--source-only', '--out', nativeProjectionSourcePath], { log: (value = '') => lines.push(String(value)) });
assert.equal(lines.length, 0);
assert.equal(readFileSync(nativeProjectionSourcePath, 'utf8'), readFileSync(nativePath, 'utf8'));
lines.length = 0;
await runCli(['native-compile', nativePath, '--parser', 'estree'], { log: (value = '') => lines.push(String(value)) });
const nativeCompile = JSON.parse(lines.join('\n'));
assert.equal(nativeCompile.kind, 'frontier.lang.nativeSourceCompileResult');
assert.equal(nativeCompile.target, 'javascript');
assert.equal(nativeCompile.language, 'javascript');
assert.equal(nativeCompile.outputMode, 'preserved-source');
assert.equal(nativeCompile.output, readFileSync(nativePath, 'utf8'));
assert.equal(nativeCompile.metadata.sameSourceTarget, true);
assert.equal(nativeCompile.evidence.some((entry) => entry.id.includes('native_source_compile')), true);
lines.length = 0;
await runCli(['native-compile', nativeOutPath, '--target', 'rust'], { log: (value = '') => lines.push(String(value)) });
const nativeCompileBlocked = JSON.parse(lines.join('\n'));
assert.equal(nativeCompileBlocked.target, 'rust');
assert.equal(nativeCompileBlocked.ok, false);
assert.equal(nativeCompileBlocked.outputMode, 'target-stubs');
assert.equal(nativeCompileBlocked.targetCoverage.lossClass, 'missingAdapter');
assert.equal(nativeCompileBlocked.readiness.readiness, 'blocked');
assert.match(nativeCompileBlocked.output, /pub fn addTodo/);
const nativeCompileRustOutPath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-native-compile-out-')), 'todo.rs');
lines.length = 0;
await runCli(['native-compile', nativeOutPath, '--target', 'rust', '--emit-on-blocked', '--source-only', '--out', nativeCompileRustOutPath], { log: (value = '') => lines.push(String(value)) });
assert.equal(lines.length, 0);
assert.match(readFileSync(nativeCompileRustOutPath, 'utf8'), /pub fn addTodo/);
lines.length = 0;
await runCli(['project-native', nativePath, '--stubs'], { log: (value = '') => lines.push(String(value)) });
const nativeStubProjection = JSON.parse(lines.join('\n'));
assert.equal(nativeStubProjection.mode, 'native-source-stubs');
assert.equal(nativeStubProjection.lossSummary.categories.includes('targetProjectionLoss'), true);
lines.length = 0;
await runCli(['native-coverage', nativePath, '--parser', 'estree'], { log: (value = '') => lines.push(String(value)) });
const nativeCoverage = JSON.parse(lines.join('\n'));
assert.equal(nativeCoverage.kind, 'frontier.lang.nativeImportCoverageMatrix');
assert.equal(nativeCoverage.summary.imports, 1);
lines.length = 0;
await runCli(['native-capabilities', nativePath, '--parser', 'estree', '--target', 'rust'], { log: (value = '') => lines.push(String(value)) });
const nativeCapabilities = JSON.parse(lines.join('\n'));
assert.equal(nativeCapabilities.kind, 'frontier.lang.universalCapabilityMatrix');
assert.equal(nativeCapabilities.languages.length, 1);
assert.equal(nativeCapabilities.languages[0].language, 'javascript');
assert.equal(nativeCapabilities.summary.imports, 1);
assert.deepEqual(nativeCapabilities.metadata.compileTargets, ['rust']);
const nativeAfterPath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-native-after-')), 'todo.js');
writeFileSync(nativeAfterPath, 'export function addTodo() { return null; }\nexport function clearTodos() { return []; }\n');
lines.length = 0;
await runCli(['native-diff', nativePath, '--after', nativeAfterPath, '--parser', 'estree'], { log: (value = '') => lines.push(String(value)) });
const nativeDiff = JSON.parse(lines.join('\n'));
assert.equal(nativeDiff.kind, 'frontier.lang.nativeSourceChangeSet');
assert.equal(nativeDiff.summary.sourceChanged, true);
assert.equal(nativeDiff.summary.addedSymbols >= 1, true);
assert.equal(nativeDiff.mergeCandidate.kind, 'frontier.lang.semanticMergeCandidate');
const phpPath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-native-php-')), 'todo.php');
writeFileSync(phpPath, '<?php\nfunction addTodo($title) {}\n');
lines.length = 0;
await runCli(['import', phpPath], { log: (value = '') => lines.push(String(value)) });
const phpImport = JSON.parse(lines.join('\n'));
assert.equal(phpImport.language, 'php');
assert.equal(phpImport.semanticIndex.symbols.some((symbol) => symbol.name === 'addTodo'), true);
const rubyPath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-native-ruby-')), 'todo.rb');
writeFileSync(rubyPath, 'def add_todo(title)\nend\n');
lines.length = 0;
await runCli(['import', rubyPath], { log: (value = '') => lines.push(String(value)) });
const rubyImport = JSON.parse(lines.join('\n'));
assert.equal(rubyImport.language, 'ruby');
assert.equal(rubyImport.semanticIndex.symbols.some((symbol) => symbol.name === 'add_todo'), true);
const corpusDir = mkdtempSync(join(tmpdir(), 'frontier-lang-corpus-'));
writeFileSync(join(corpusDir, 'fixture.frontier'), readFileSync('test/fixture.frontier', 'utf8'));
writeFileSync(join(corpusDir, 'todo.php'), '<?php\nfunction addTodo($title) {}\n');
writeFileSync(join(corpusDir, 'todo.rb'), 'def add_todo(title)\nend\n');
mkdirSync(join(corpusDir, 'node_modules'));
writeFileSync(join(corpusDir, 'node_modules', 'ignored.js'), 'export function ignored() {}');
lines.length = 0;
await runCli(['corpus-roundtrip', corpusDir, '--target', 'typescript'], { log: (value = '') => lines.push(String(value)) });
const corpusRoundtrip = JSON.parse(lines.join('\n'));
assert.equal(corpusRoundtrip.kind, 'frontier.lang.corpusRoundtrip');
assert.equal(corpusRoundtrip.total, 3);
assert.equal(corpusRoundtrip.failed, 0);
assert.ok(corpusRoundtrip.sourceMapCount >= 2);
assert.ok(corpusRoundtrip.lossCount >= 2);
assert.ok(corpusRoundtrip.sourcePreservationCount >= 2);
assert.ok(corpusRoundtrip.projectionModes['preserved-source'] >= 2);
assert.ok(corpusRoundtrip.readiness['needs-review'] >= 2);
assert.equal(corpusRoundtrip.files.some((entry) => entry.language === 'php'), true);
assert.equal(corpusRoundtrip.files.some((entry) => entry.language === 'ruby'), true);
const corpusOutPath = join(mkdtempSync(join(tmpdir(), 'frontier-lang-corpus-out-')), 'corpus.json');
lines.length = 0;
await runCli(['corpus-roundtrip', corpusDir, '--target', 'typescript', '--out', corpusOutPath], { log: (value = '') => lines.push(String(value)) });
assert.equal(lines.length, 0);
const corpusOut = JSON.parse(readFileSync(corpusOutPath, 'utf8'));
assert.equal(corpusOut.kind, 'frontier.lang.corpusRoundtrip');

const binDir = mkdtempSync(join(tmpdir(), 'frontier-lang-cli-bin-'));
const binPath = join(binDir, 'frontier-lang');
symlinkSync(join(process.cwd(), 'dist/index.js'), binPath);
const binRun = spawnSync(process.execPath, [binPath, 'hash', 'test/fixture.frontier'], { encoding: 'utf8' });
assert.equal(binRun.status, 0, binRun.stderr);
assert.match(binRun.stdout.trim(), /^fnv1a32:/);
